---

# The following section provides configuration for the web server embedded within
# this application.
server:
  port: 8080
  error:
    include-message: always

# The following section is configuration specific to the spring-boot (i.e. spring)
# framework.
spring:
  main:
    banner-mode: off
  application:
    name: hospital-manager
  # The jdbc (java database connectivity) connection url string required to connect
  # to the sql database. We are using a PostgreSQL database here.
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username:
    password:
  # The jpa (java persistence api) configuration. Hibernate is used as the
  # implementation for this application's persistence layer.
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true